name: Build

permissions:
  contents: write

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: |
          mkdir -p dist

      - name: Build For Linux ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          push: false
          file: build.Dockerfile
          platforms: linux/${{ matrix.platform }}
          outputs: type=local,dest=./dist
          cache-from: type=gha
          cache-to: type=gha

      - run: |
          mv dist/hivereg-linux dist/hivereg-linux_${{ matrix.platform }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.platform }}
          path: |
            dist/

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          pattern: dist-*
          path: dist/
      - run: |
          find dist/ | xargs ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*/hivereg-*